GET http://localhost:3000/api

###

GET http://localhost:3000/api/get-all-teams

###

GET http://localhost:3000/api/get-team/1 

###

POST http://localhost:3000/api/save-new-team
Content-Type: application/json

{
    "id": "101",
    "name": "test101",
    "pkmn": ["1", "2", "3", "4", "5", "6"]
}

###

PUT http://localhost:3000/api/update-team/1
Content-Type: application/json

{   
    "name": "bytaTest101",
    "pkmn": ["7", "8", "9", "10", "11", "12"]
}

###

DELETE http://localhost:3000/api/delete-team/1

